[package]
name = "azutreo/new-chat-controller"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Knit and Util
Knit = "sleitnick/knit@^1.2"
Signal = "sleitnick/signal@1.1.0"
# Timer = "sleitnick/timer@1.1.1"
# WaitFor = "sleitnick/wait-for@0.2.0"
# Log = "sleitnick/log@0.1.0"
Input = "sleitnick/input@1.3.1"
Component = "sleitnick/component@2.4.2"
TableUtil = "sleitnick/table-util@1.1.1"
TaskQueue = "sleitnick/task-queue@0.1.0"
# Shake = "sleitnick/shake@0.1.3"
EnumList = "sleitnick/enum-list@2.0.0"

# Extra
Promise = "evaera/promise@3.2.1"
# Roact = "roblox/roact@1.4.2"
# Janitor = "howmanysmall/janitor@1.13.15"
TestEz = "roblox/testez@0.4.1"

[server-dependencies]
Cmdr = "evaera/cmdr@1.8.4"