name: Run selene
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Remove ignored files
      run: rm DataStore2/Promise.lua
    # std chaining with roblox is broken
    - name: Generate standard library
      run: selene generate-roblox-std
    - name: Run Selene
      run: selene .
